In [45]:
import pandas as pd
from sqlalchemy import create_engine

In [46]:
df = pd.read_csv(r"C:\Users\Isabe\Downloads\g11_Delivery_warehouses.csv", sep=";", parse_dates=['order_date','created_date'], dayfirst=True)

In [47]:
df_order = df.loc[:, ["cost", "order_date"]]

In [48]:
df_order = df_order.dropna(subset=["cost", "order_date"])

In [49]:
df_order.insert(0, "id", range(1, len(df_order) + 1))

In [50]:
df_order["id"] = df_order["id"].astype(int)

In [51]:
df_order["cost"] = df_order["cost"].astype(int)

In [52]:
df_order.head(3)

   id  cost order_date
0   1  4797 2023-08-01
1   2  1585 2024-10-09
2   3  1010 2023-10-29

In [53]:
engine = create_engine('sqlite:///DATABASEFINAL.db')

In [54]:
df_order.to_sql('order', con=engine, if_exists='replace', index=False)

10598

In [55]:
result = pd.read_sql('SELECT * FROM "order"', con=engine)

In [56]:
result.head(3)

   id  cost                  order_date
0   1  4797  2023-08-01 00:00:00.000000
1   2  1585  2024-10-09 00:00:00.000000
2   3  1010  2023-10-29 00:00:00.000000

In [57]:
df_order.to_csv("order.csv", sep=";", index=False)

In [58]:
engine.dispose()