In [11]:
import pandas as pd
from sqlalchemy import create_engine

In [12]:
df = pd.read_csv(r"g11_Delivery_warehouses.csv", sep=";", parse_dates=['order_date','created_date'], dayfirst=True)

In [13]:
df.columns = df.columns.str.strip()

In [14]:
list(df.columns)

['company_id',
 'warehouse_id',
 'order_date',
 'cost',
 'name',
 'created_date',
 'designation',
 'type',
 'vehicle_id',
 'comments']

In [15]:
df_vehicle = df.loc[:, ["vehicle_id", "comments"]]

In [16]:
df_vehicle = df_vehicle.drop_duplicates()

In [17]:
df_vehicle.insert(0, "id", range(1, len(df_vehicle) + 1))

In [18]:
df_vehicle["id"] = df_vehicle["id"].astype(int)

In [19]:
df_vehicle.head(3)

   id  vehicle_id comments
0   1         NaN      NaN
4   2        28.0   remain
5   3       121.0    stock

In [20]:
engine = create_engine("sqlite:///DATABASEFINAL.db")

In [21]:
df_vehicle.to_sql("vehicle", con=engine, if_exists="replace", index=False)

201

In [22]:
result = pd.read_sql('SELECT * FROM vehicle', con=engine)

In [23]:
result.head(3)

   id  vehicle_id comments
0   1         NaN     None
1   2        28.0   remain
2   3       121.0    stock

In [24]:
df_vehicle.to_csv("vehicle.csv", sep=";", index=False)