In [242]:
import pandas as pd
from sqlalchemy import create_engine

In [243]:
df = pd.read_csv("g11_Delivery_warehouses.csv", sep = ';', parse_dates=['order_date','created_date'], dayfirst=True)

In [244]:
df_warehouse = df.loc[:, ['warehouse_id', 'designation', 'type']]

In [245]:
df_warehouse = df_warehouse.dropna(subset=['warehouse_id', 'designation', 'type'])

In [246]:
df_warehouse = df_warehouse.drop_duplicates(subset='warehouse_id', keep='first')

In [247]:
df_warehouse['warehouse_id'] = df_warehouse['warehouse_id'].astype(int)

In [248]:
df_warehouse.rename(columns={'warehouse_id': 'id'}, inplace=True)

In [249]:
df_warehouse.head(3)

    id  designation                                 type
0   58     New York                  Automated Warehouse
1  436  Los Angeles                  Cold Storage Center
2   20      Chicago  Climate-Controlled Distribution Hub

In [250]:
engine = create_engine('sqlite:///DATABASEFINAL.db')

In [251]:
df_warehouse.to_sql('warehouse', con=engine, if_exists='replace', index=False)

1000

In [252]:
result = pd.read_sql('SELECT * FROM Warehouse', con=engine)

In [253]:
result.head(3)

    id  designation                                 type
0   58     New York                  Automated Warehouse
1  436  Los Angeles                  Cold Storage Center
2   20      Chicago  Climate-Controlled Distribution Hub

In [254]:
df_warehouse.to_csv('warehouse.csv', sep=';', index=False)

In [255]:
engine.dispose()